### ISSUE TITLE
Dotted lines?

### ISSUE THREAD

**Issue by vincecr0ft** [GkAntonius/feynman#1]
I've been using these libraries for a long time with my research in Higgs searches, measurements, and modelling. These libraries make a great addition to [my demonstrations](https://www.nikhef.nl/~vcroft/notebooks.html) for using notebooks for data analysis at CERN. 

But... dotted lines for the Higgs/invisible particles would be a great (and easy) addition. Would this be possible?

**Comment by GkAntonius** [comment]
Hi Vince, I am glad to see that my module is useful to other physicists.

I have made a quick implementation of dotted lines. So the keyword 'dotted' can now be passed as a stroke (to replace 'single' or 'double'). In the long run I plan to do a more fancy implementation of dotted lines.

By the way, I do solid state physics, so the kind of diagrams I draw are not the same as those used in particle physics. Your examples however might be useful to other users. Please consider contributing them to the example directory.

**Comment by vincecr0ft** [comment]
Oh idiot me. Dashed I meant dashed lines! I'm sorry. This is a wonderful implementation of exactly what I asked for. But unfortunately not what I meant. Is is possible to also add dashed lines?
like this ![Higgles](http://ihp-lx.ethz.ch/CompMethPP/higgsL3/pictures/higgsstrahlung.jpg)

I especially like your libraries because it lets me write this sort of code using Jupyter. Do you want me to add the notebooks like on the [webpage](https://www.nikhef.nl/~vcroft/HiggsFeynmanDiagrams.html)? I can easily tidy it up if you like it.

**Comment by vincecr0ft** [comment]
And now I see that you already added dashed and dotted lines. That's really great!
