### ISSUE TITLE
change color of arrows

### ISSUE THREAD

**Issue by dfaroughy** [GkAntonius/feynman#4]
Is there a simple way to change the color of the arrows?  I just want the arrow color to match the line color.  Thanks!

**Comment by GkAntonius** [comment]
You can specify the arrow color and properties like this (see the [line API doc](http://gkantonius.github.io/feynman/line.html))
```
import matplotlib.pyplot as plt
from feynman import Diagram
D = Diagram()
v1 = D.vertex(xy=(0.1,0.5))
v2 = D.vertex(v1.xy, dx=0.5)
G = D.line(v1, v2, style='single', arrow=True, color='b',  arrow_param={'width':0.05, 'color':'b'})
D.plot()
plt.show()
```
At the moment, there is no automatic way to have the arrow color match the line.

**Comment by dfaroughy** [comment]
that is great! thanks!
