### ISSUE TITLE
New release on PyPI?

### ISSUE THREAD

**Issue by APN-Pucky** [GkAntonius/feynman#8]
I'd like to request a new release on PyPI with recent fixes.
PyPI still has 2.0.2 from 2018 and I am running into those issues with that version (https://github.com/APN-Pucky/pyfeyn2/pull/114 https://github.com/APN-Pucky/pyfeyn2/pull/118).

**Comment by GkAntonius** [comment]
Dear Pucky,
Indeed, a new PyPI release was needed. I have uploaded the latest version.
Cheers,

**Comment by APN-Pucky** [comment]
Thanks!
